obsolete detectors
pessimistic-io/slitherin pull request #163
Opened 2024-05-30 07:14 UTC by Yhtiyar

2024-06-01 10:08 UTC, ndkirillov requested changes
Let's:
- add a flag to the cli for the convenience
- mark obsolete detectors in docs (create a new directory or directly in .md)

2024-06-01 10:08 UTC, ndkirillov commented on slitherin/consts.py
Shouldn't we also add the handle of the parameter to the **cli.py** file?

2024-06-01 10:08 UTC, ndkirillov commented on slitherin/detectors/obsolete/README.md
But where to set this flag?

2024-06-03 05:24 UTC, Yhtiyar commented on slitherin/detectors/obsolete/README.md
in bash:
``` bash
$ export SLITHERIN_OBSOLETE=true
$ slitherin ...
```

2024-06-04 07:27 UTC, ndkirillov commented on slitherin/detectors/obsolete/README.md
Ok!

2024-06-04 07:28 UTC, ndkirillov approved these changes
LGTM

2024-06-04 10:55 UTC, merged