Arbitrary call
pessimistic-io/slitherin pull request #66
Opened 2023-08-22 07:45 UTC by Yhtiyar

2023-08-24 09:31 UTC, Yhtiyar commented
@ndkirillov  I forgot to add `.md` description :(
Will add today

2023-08-24 10:59 UTC, Yhtiyar commented
fixed, ready for review

2023-08-24 15:10 UTC, ndkirillov requested changes
Some changes are needed in the documentation file. Please check the related comment.

2023-08-24 15:10 UTC, ndkirillov commented on docs/arbitrary_call.md
Lines 1-7 and 13-15 are from the other detector. Please change to the PRs' subject detectors.

2023-08-29 07:48 UTC, Yhtiyar commented on slither_pess/detectors/arbitrary_call.py
added

2023-08-29 07:49 UTC, Yhtiyar commented on docs/arbitrary_call.md
fixed

2023-08-29 07:51 UTC, ndkirillov approved these changes
All good now

2023-08-29 07:51 UTC, merged